import React, { useEffect } from "react";
import "./home.css";
import "./../../data";
import largeImgCard1 from "../../assets/l_card_picture_p1.png";
import smallImgCard1 from "../../assets/m_card_picture_p1.png";
import { useLocation } from "react-router-dom";
import { useGSAP } from "@gsap/react";
import gsap from "gsap";
import Card from "../../components/card/Card";

const getConfig = (trigger, startColor, endColor) => {
  return {
    scrollTrigger: {
      trigger: trigger,
      scrub: true,
      markers: true,
      start: "top 80%",
      end: "top 20%",
    },
    startAt: { backgroundColor: startColor, "--background-color": startColor },
    backgroundColor: endColor,
    "--background-color": endColor,
  };
};

const Home = () => {
  useGSAP(() => {
    gsap
      .timeline()
      .set("body", {
        backgroundColor: "#c4b9c0",
        "--background-color": "#c4b9c0",
      })
      .to("body", getConfig("#one", "#c4b9c0", "#c3c2cb"))
      .to("body", getConfig("#two", "#c3c2cb", "#cd5c5c"))
      .to("body", getConfig("#three", "#cd5c5c", "#cd5c5c"));
  });

  const location = useLocation();

  useEffect(() => {
    if (location.hash) {
      document
        .querySelector(location.hash)
        ?.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, [location]);

  return (
    <>
      <section id="test" style={{ margin: "800px 0" }}>
        <div id="one" style={{ height: 1000, borderBottom: "solid 1px" }}></div>
        <div id="two" style={{ height: 1000, borderBottom: "solid 1px" }}></div>
        <div
          id="three"
          style={{ height: 1000, borderBottom: "solid 1px" }}
        ></div>
        <div
          id="four"
          style={{ height: 1000, borderBottom: "solid 1px" }}
        ></div>
      </section>
      <div className="hero-container">
        <h3 className="name">Hello there! I’m Liwia</h3>
        <div className="hero-intro">
          <span>
            I create interactive data visualization products that provide
            insights and help people make data driven decisions.{" "}
          </span>
          Currently Senior Business Intelligence Analyst doing research, design
          and development of finance reporting solutions at EcoVadis.
        </div>
        <div className="projects">
          <h2 className="projects-title">TOP PROJECTS</h2>
        </div>
        <div>
          {cards.map((card, index) => (
            <Card key={index} card={card} />
          ))}
        </div>
        <div className="projects">
          <h2 className="projects-title">ALL PROJECTS</h2>
        </div>
      </div>
      <div id="view" style={{ marginTop: 1000 }}>
        VIEW
      </div>
    </>
  );
};

export default Home;

const cards = [
  {
    title: "Business Application for Supply Chain Optimization",
    description: `Using Figma to design a digital experience and solve client data experience challenge.
    Over the course of eight weeks I conducted Data Experience (DX) research, designed and prototyped business application aimed at optimizing clients’ supply chain network.`,
    tools:
      "Figma * DX Research * Data Viz Design * Product Design * UX/UI Design",
    img_large: (
      <img
        src={largeImgCard1}
        alt="Sample pictures of data visualization project."
      />
    ),
    img_small: (
      <img
        src={smallImgCard1}
        alt="Sample pictures of data visualization project."
      />
    ),
  },
  {
    title: "Sustainable Travel: Company’s Carbon Emission Analysis",
    description:
      "A Tableau dashboard has been created to enable companies to track the carbon emissions generated by business flight travel. This dashboard allows companies to identify problematic areas within their organization that contribute to the highest carbon emissions. Based on these insights, companies can plan effective carbon reduction strategies.",
    tools: "Tableau * SQL * Data Viz Design * Data Modelling * Data Processing",
  },
  {
    title: "Iris Species: Charting for Multiple Measures",
    description:
      "The private project focused on visualizing the Iris Species dataset. To analyze the main metrics, I used scatterplot matrix and parallel coordinates charts. While these types of visualizations are not commonly used in business reporting, they are frequently employed in the statistical field.",
    tools: "d3.js * Data Viz Design",
  },
  {
    title: `Google BI Certificate:
    Cyclistic Capstone Project`,
    description:
      "The capstone project of preparing Cyclistic’s customer analysis serves as final assignment for Google Business Intelligence Professional Certification.",
    tools: "Tableau * Mapbox * SQL * Data Analysis * Data Viz Design",
  },
];
