import desktopImgCard1 from "../src/assets/d_card_picture_p1.png";
import mobileImgCard1 from "../src/assets/m_card_picture_p1.png";
import desktopImgCard2 from "../src/assets/d_card_picture_p2.png";
import mobileImgCard2 from "../src/assets/m_card_picture_p2.png";
import desktopImgCard3 from "../src/assets/d_card_picture_p3.png";
import mobileImgCard3 from "../src/assets/m_card_picture_p3.png";
import desktopImgCard4 from "../src/assets/d_card_picture_p4.png";
import mobileImgCard4 from "../src/assets/m_card_picture_p4.png";

export const cards = [
  {
    id: 1,
    htmlId: "one",
    gsap: {
      id: "#one",
      toColor: "#E0D5DC",
    },
    order: 4,
    title:
      "Enhancing Efficiency: Business Application for Supply Chain Optimization",
    description: `I used Figma to design a digital solution that addressed a client’s data experience challenges, focusing on optimizing their supply chain network. Over an eight-week period, I conducted extensive Data Experience (DX) research, which informed the design and prototyping of a business application aimed at streamlining and enhancing the efficiency of their operations.`,
    tools:
      "Figma + DX Research + Data Viz Design + Product Design + UX/UI Design",
    backgroundColor: "var(--bc-project-id1)",
    btn: {
      text: "GO TO PROJECT",
      color: "var(--btn-project-id1)",
      aLink: "./pages/project_network_edge/ProjectNetworkEdge.jsx",
    },
    images: {
      desktop: {
        src: desktopImgCard1,
      },
      mobile: {
        src: mobileImgCard1,
        positionBottom: "-1rem",
        positionRight: "-4rem",
      },
    },
  },
  {
    id: 2,
    htmlId: "two",
    gsap: {
      id: "#two",
      toColor: "#D8D6E8",
    },
    order: 1,
    title:
      "Sustainable Business Travel: A Data-Driven Carbon Emission Analysis",
    description: `I designed and developed a Tableau dashboard that enables companies to track and analyze carbon emissions generated by business air travel. The dashboard helps organizations pinpoint the areas contributing the most to their emissions, providing actionable insights to guide the development of targeted carbon reduction strategies for more sustainable operations.`,
    tools:
      "Tableau + SQL + Dashboard Design + Data Viz Design + Data Modelling + Data Processing",
    backgroundColor: "var(--bc-project-id2)",
    btn: {
      text: "GO TO PROJECT",
      color: "var(--btn-project-id2)",
      aLink: "../project_sustainable_travel/ProjectSustainableTravel.jsx",
    },
    images: {
      desktop: {
        src: desktopImgCard2,
        positionBottom: "-2rem",
      },
      mobile: {
        src: mobileImgCard2,
        positionBottom: "-1.2rem",
        positionRight: "-1.6rem",
      },
    },
  },
  {
    id: 3,
    htmlId: "three",
    gsap: {
      id: "#three",
      toColor: "#EFEEF8",
    },
    order: 3,
    title:
      "Visualizing Iris Species: A Comparative Analysis of Multiple Measures",
    description: `In this private project, I focused on visualizing the Iris Species dataset by utilizing scatterplot matrix and parallel coordinates charts to analyze key metrics. Although these visualizations are not typically used in business reporting, they are widely applied in statistical analysis for their ability to reveal complex patterns and relationships within the data. Through this approach, I was able to gain deeper insights into the distribution and correlations among the dataset's features.`,
    tools: "d3.js + Data Viz Design",
    backgroundColor: "var(--bc-project-id3)",
    btn: {
      text: "GO TO OBSERVABLE NOTEBOOK",
      color: "var(--btn-project-id3)",
      refLink: "https://observablehq.com/d/40e11c389ce691ef",
    },
    images: {
      desktop: {
        src: desktopImgCard3,
        positionBottom: "-1.4rem",
      },
      mobile: {
        src: mobileImgCard3,
        positionBottom: "-2.4rem",
        positionRight: "-1rem",
      },
    },
  },
  {
    id: 4,
    htmlId: "four",
    gsap: {
      id: "#four",
      toColor: "#E9EEF0",
    },
    order: 2,
    title: `Cyclistic Case Study: A Capstone Project for Google BI Certification`,
    description: `
    The capstone project, focused on preparing Cyclistic’s customer analysis, serves as the final assignment for the Google Business Intelligence Professional Certification, demonstrating the application of advanced BI skills in a real-world business context. This project not only reinforces technical expertise but also highlights the ability to derive actionable insights from data to support business decisions.`,
    tools:
      "Tableau + Mapbox + SQL + Data Viz Design + Data Analysis + Data Modelling + Data Processing",
    backgroundColor: "var(--bc-project-id4)",
    btn: {
      text: "GO TO PROJECT",
      color: "var(--btn-project-id4)",
      aLink: "../project_cyclistic/ProjectCyclistic",
    },
    images: {
      desktop: {
        src: desktopImgCard4,
        positionBottom: "-2.4rem",
      },
      mobile: {
        src: mobileImgCard4,
        positionBottom: "-1.6rem",
        positionRight: "-1.6rem",
      },
    },
  },
];

export const projects = [
  {
    id: 1,
    title: `Enhancing Efficiency: Business Application for Supply Chain
    Optimization`,
    introTypes: [
      {
        title11: "THE PRODUCT",
        paragraph11: `I conducted Data Experience (DX) research and took the lead in
        designing and prototyping a business application specifically
        aimed at optimizing clients' supply chain networks. This involved
        thoroughly analyzing data patterns, identifying key bottlenecks,
        and ensuring the application catered to the unique logistical
        needs of each client. Through a combination of advanced data
        visualization techniques and user-centered design, I created a
        tool that improved efficiency, enhanced decision-making, and
        streamlined operations across various stages of the supply chain.`,
      },
      {
        title12: "THE PROBLEM",
        paragraph12: `The client's reporting solution had not been updated or analyzed
        for user experience since its launch over two years ago. As a
        result, the design had likely fallen behind evolving user needs
        and modern usability standards. Without regular assessments,
        potential usability issues, inefficiencies, and areas for
        improvement had gone unnoticed, affecting the tool's overall
        effectiveness and user satisfaction. Additionally, the system had
        not taken advantage of newer design trends, technologies, or
        updated user interaction patterns during that time.`,
      },
      {
        title13: "THE GOAL",
        paragraph13: `The primary objective of the project was to gain a comprehensive
        understanding of the user experience and subsequently redesign the
        existing reporting solution informed by user feedback. This
        involved conducting detailed user research, including interviews
        and usability testing, to gather insights into how users
        interacted with the current system. Based on this feedback, we
        aimed to identify pain points and areas for improvement, ensuring
        that the redesigned solution would effectively address user needs
        and enhance overall satisfaction. The ultimate goal was to create
        a more intuitive and efficient reporting tool that aligned with
        users' expectations and facilitated better decision-making.`,
      },
    ],
    areasOfExpertise: {
      title: "AREAS OF EXPERTISE",
      content: " Product Design + Data Viz Design + UX/UI Design + DX Research",
    },
    tools: { title: "TOOLS & PROGRAMMING LANGUAGES", content: "Figma" },
    deliveryDate: { title: "DELIVERY DATE", content: "March 2022" },
  },
  {
    id: 2,
    title:
      "Sustainable Business Travel: A Data-Driven Carbon Emission Analysis",
    introType1: {
      title: "THE PRODUCT",
      paragraph: "",
    },
    introType1: {
      title: "THE PROBLEM",
      paragraph: "",
    },
    introType1: {
      title: "THE GOAL",
      paragraph: "",
    },

    areasOfExpertise: {
      title: "AREAS OF EXPERTISE",
      content:
        "Dashboard Design + Data Viz Design + Data Modelling + Data Processing",
    },
    tools: { title: "TOOLS & PROGRAMMING LANGUAGES", content: "Tableau + SQL" },
    deliveryDate: { title: "DELIVERY DATE", content: "March 2024" },
  },
  {
    id: 4,
    title: `Cyclistic Case Study: A Capstone Project for Google BI Certification`,
    introTypes: [
      {
        paragraph21:
          "The capstone project of preparing Cyclistic’s customer analysis serves as the final assignment for the Google Business Intelligence Professional Certification. In this case, I assume the role of a Junior Data Analyst at the fictional bike-share company, Cyclistic. In 2016, Cyclistic launched a successful bike-share offering with a fleet of 5,824 bicycles tracked and locked into a network of 692 stations across Chicago.",
      },
      {
        paragraph22:
          "The bikes can be unlocked from one station and returned to any other station in the system at any time. Riders with an annual subscription are called members, while riders using single-ride or full-day passes are considered casual riders.",
      },
      {
        paragraph23:
          "The director of marketing aims to maximize the number of annual memberships, as they are more profitable than single-ride or full-day passes. This strategy is believed to be key to future growth. The primary goal of the analysis is to understand the behaviors of Cyclistic’s two main user groups: members and casual riders.",
      },
    ],
    areasOfExpertise: {
      title: "AREAS OF EXPERTISE",
      content:
        "Data Analysis + Data Viz Design + Data Modelling + Data Processing",
    },
    tools: {
      title: "TOOLS & PROGRAMMING LANGUAGES",
      content: "Tableau + Mapbox + SQL",
    },
    deliveryDate: { title: "DELIVERY DATE", content: "May 2023" },
  },
];
