import desktopImgCard1 from "../src/assets/d_card_picture_p1.png";
import mobileImgCard1 from "../src/assets/m_card_picture_p1.png";
import desktopImgCard2 from "../src/assets/d_card_picture_p2.png";
import mobileImgCard2 from "../src/assets/m_card_picture_p2.png";
import desktopImgCard3 from "../src/assets/d_card_picture_p3.png";
import mobileImgCard3 from "../src/assets/m_card_picture_p3.png";
import desktopImgCard4 from "../src/assets/d_card_picture_p4.png";
import mobileImgCard4 from "../src/assets/m_card_picture_p4.png";

export const cards = [
  {
    id: 1,
    title: "Business Application for Supply Chain Optimization",
    description: `Using Figma to design a digital experience and solve client data experience challenge.
    Over the course of eight weeks I conducted Data Experience (DX) research, designed and prototyped business application aimed at optimizing clients’ supply chain network.`,
    tools:
      "Figma + DX Research + Data Viz Design + Product Design + UX/UI Design",
    img_desktop: (
      <img
        src={desktopImgCard1}
        alt="Sample pictures of data visualization project."
      />
    ),
    img_mobile: (
      <img
        src={mobileImgCard1}
        alt="Sample pictures of data visualization project."
      />
    ),
  },
  {
    id: 2,
    title: "Sustainable Travel: Company’s Carbon Emission Analysis",
    description:
      "A Tableau dashboard has been created to enable companies to track the carbon emissions generated by business flight travel. This dashboard allows companies to identify problematic areas within their organization that contribute to the highest carbon emissions. Based on these insights, companies can plan effective carbon reduction strategies.",
    tools: "Tableau + SQL + Data Viz Design + Data Modelling + Data Processing",
    img_desktop: (
      <img
        src={desktopImgCard2}
        alt="Sample pictures of data visualization project."
      />
    ),
    img_mobile: (
      <img
        src={mobileImgCard2}
        alt="Sample pictures of data visualization project."
      />
    ),
  },
  {
    id: 3,
    title: "Iris Species: Charting for Multiple Measures",
    description:
      "The private project focused on visualizing the Iris Species dataset. To analyze the main metrics, I used scatterplot matrix and parallel coordinates charts. While these types of visualizations are not commonly used in business reporting, they are frequently employed in the statistical field.",
    tools: "d3.js + Data Viz Design",
    img_desktop: (
      <img
        src={desktopImgCard3}
        alt="Sample pictures of data visualization project."
      />
    ),
    img_mobile: (
      <img
        src={mobileImgCard3}
        alt="Sample pictures of data visualization project."
      />
    ),
  },
  {
    id: 4,
    title: `Google BI Certificate:
    Cyclistic Capstone Project`,
    description:
      "The capstone project of preparing Cyclistic’s customer analysis serves as final assignment for Google Business Intelligence Professional Certification.",
    tools: "Tableau + Mapbox + SQL + Data Analysis + Data Viz Design",
    img_desktop: (
      <img
        src={desktopImgCard4}
        alt="Sample pictures of data visualization project."
      />
    ),
    img_mobile: (
      <img
        src={mobileImgCard4}
        alt="Sample pictures of data visualization project."
      />
    ),
  },
];
